[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"

[language-server.tailwindcss-ls-ex]
command = "tailwindcss-language-server"
args = ["--stdio"]
config = { tailwindCSS = { includeLanguages = { "elixir" = "html", "heex" = "html" }, experimental = { configFile = "assets/css/app.css" } } } 

[language-server.vscode-css-language-server]
args                       = ["--stdio"]
command                    = "vscode-css-language-server"
config.css.validate.enable = true
config.provideFormatter    = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls"]
formatter = { command = "prettier", args = ["--parser", "typescript"]}
file-types = ["tsx", "ts"]
auto-format = true

[[language]]
name = "elixir"
formatter = { command = "mix", args = ["format", "--stdin-filename", "%{buffer_name}", "-"] }
roots = ["mix.exs"]
auto-format = true
diagnostic-severity = "hint"
comment-token = "#"
indent = {tab-width = 2, unit = " "}
language-servers = ["elixir-ls", "tailwindcss-ls-ex"]

[[language]]
name = "heex"
auto-format = true
language-servers = ["elixir-ls", "tailwindcss-ls-ex", "vscode-html-language-server"]

